name: delivery_app
description: Delivery app from Flutter course
publish_to: 'none'
version: 0.5.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5



flutter:
  uses-material-design: true
  assets:
    - assets/images/home/background/
    - assets/images/home/chevron_right/
    - assets/images/menu/menuicon/
    - assets/images/menu/bag/fill/
    - assets/images/bag/chevron_left/
    - assets/images/bag/background/
    - assets/images/pizza/background/
    - assets/images/pizza/star_grey/
        
    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.otf


