name: delivery_app
description: Delivery app from Flutter course
publish_to: 'none'
version: 0.5.5

environment:
  sdk: '>=3.0.5 <4.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  hive_generator: 
  build_runner: 


flutter:
  uses-material-design: true
  assets:
    - assets/images/home/background/
    - assets/images/home/chevron_right/
    - assets/images/menu/menuicon/
    - assets/images/menu/bag/
    - assets/images/bag/chevron_left/
    - assets/images/bag/background/
    - assets/images/pizza/star_grey/
    - assets/images/booking/background/

    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.otf


